Restructured some tests. Added some tests and some better framework for the program. Updated list of error codes and created a macro file for them.

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -1,17 +1,39 @@
+#Useful variables to pass to the tests
 PROGNAME	= quadsolve
 PROGPLACE	= ../src/
 PROG		= $(PROGPLACE)$(PROGNAME)
 
 export PROG
 
-all : argtest
+#Error codes to pass to the tests
+
+NUMARG_ERR	= 1
+BADARG_ERR	= 2
+UNDERFLOW_ERR	= 3
+OVERFLOW_ERR	= 4
+NANARG_ERR	= 5
+
+export NUMARG_ERR BADARG_ERR UNDERFLOW_ERR OVERFLOW_ERR NANARG_ERR
+
+all : numarg badarg overflow underflow nanarg
 
 .SILENT :
-
-argtest : argtest.bash $(PROG)
-	./argtest.bash || echo "Error: $(PROG) does not pass test '$<'."
-	echo "'$<' passed successfully."
 
 $(PROG) :
 	make -C $(PROGPLACE) $(PROGNAME) || echo "Error: $(PROG) does not compile properly."
 	echo "$(PROG) compiled properly."
+
+numarg : numarg.bash $(PROG)
+	./numarg.bash && echo "'$<' passed successfully." || echo "Error: $(PROG) does not pass test '$<'."
+
+badarg : badarg.bash $(PROG)
+	./badarg.bash && echo "'$<' passed successfully." || echo "Error: $(PROG) does not pass test '$<'."
+
+overflow : overflow.bash $(PROG)
+	./overflow.bash && echo "'$<' passed successfully." || echo "Error: $(PROG) does not pass test '$<'."
+
+underflow : underflow.bash $(PROG)
+	./underflow.bash && echo "'$<' passed successfully." || echo "Error: $(PROG) does not pass test '$<'."
+
+nanarg : nanarg.bash $(PROG)
+	./nanarg.bash && echo "'$<' passed successfully." || echo "Error: $(PROG) does not pass test '$<'."
